src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Membre $id_membre = null;

    #[ORM\ManyToOne(inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Vehicule $id_vehicule = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_heure_depart = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_heure_fin = null;

    #[ORM\Column]
    private ?int $prix_total = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdMembre(): ?Membre
    {
        return $this->id_membre;
    }

    public function setIdMembre(?Membre $id_membre): static
    {
        $this->id_membre = $id_membre;

        return $this;
    }

    public function getIdVehicule(): ?Vehicule
    {
        return $this->id_vehicule;
    }

    public function setIdVehicule(?Vehicule $id_vehicule): static
    {
        $this->id_vehicule = $id_vehicule;

        return $this;
    }

    public function getDateHeureDepart(): ?\DateTimeInterface
    {
        return $this->date_heure_depart;
    }

    public function setDateHeureDepart(\DateTimeInterface $date_heure_depart): static
    {
        $this->date_heure_depart = $date_heure_depart;

        return $this;
    }

    public function getDateHeureFin(): ?\DateTimeInterface
    {
        return $this->date_heure_fin;
    }

    public function setDateHeureFin(\DateTimeInterface $date_heure_fin): static
    {
        $this->date_heure_fin = $date_heure_fin;

        return $this;
    }

    public function getPrixTotal(): ?int
    {
        return $this->prix_total;
    }

    public function setPrixTotal(int $prix_total): static
    {
        $this->prix_total = $prix_total;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }
}

src/Entity/Membre.php
<?php

namespace App\Entity;

use App\Repository\MembreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: MembreRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Un compte est déjà lié à cet adresse email')]
class Membre implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    #[Assert\NotBlank(message:"Ce champ ne peut pas être vide")]
    #[Assert\Regex(
        pattern: "/(\w+\.?|-?\w+?)+@\w+\.?-?\w+?(\.\w{2,3})+/",
        message: "Merci d'entrer une adresse email valide"
    )]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = ["ROLE_USER"];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 20)]
    #[Assert\NotBlank(message:"Ce champ ne peut pas être vide")]
    private ?string $pseudo = null;

    #[ORM\Column(length: 20)]
    #[Assert\NotBlank(message:"Ce champ ne peut pas être vide")]
    private ?string $nom = null;

    #[ORM\Column(length: 20)]
    #[Assert\NotBlank(message:"Ce champ ne peut pas être vide")]
    private ?string $prenom = null;

    #[ORM\Column(length: 20)]
    private ?string $civilite = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'id_membre', targetEntity: Commande::class, orphanRemoval: true)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): static
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setIdMembre($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getIdMembre() === $this) {
                $commande->setIdMembre(null);
            }
        }

        return $this;
    }
}

src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $marque = null;

    #[ORM\Column(length: 255)]
    private ?string $modele = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column]
    private ?int $prix_journalier = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_enregistrement = null;

    #[ORM\OneToMany(mappedBy: 'id_vehicule', targetEntity: Commande::class)]
    private Collection $commandes;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): static
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): static
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrixJournalier(): ?int
    {
        return $this->prix_journalier;
    }

    public function setPrixJournalier(int $prix_journalier): static
    {
        $this->prix_journalier = $prix_journalier;

        return $this;
    }

    public function getDateEnregistrement(): ?\DateTimeInterface
    {
        return $this->date_enregistrement;
    }

    public function setDateEnregistrement(\DateTimeInterface $date_enregistrement): static
    {
        $this->date_enregistrement = $date_enregistrement;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): static
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->setIdVehicule($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): static
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getIdVehicule() === $this) {
                $commande->setIdVehicule(null);
            }
        }

        return $this;
    }
}

templates/app/commande.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver un véhicule{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center mt-4">Réserver le {{ vehicule.titre }}</h1>
    {{ form_start(formCommande) }}

        {{ form_row(formCommande.date_heure_depart) }}
        {{ form_row(formCommande.date_heure_fin) }}

    <button class="btn btn-success" type="submit">Enregistrer la commande</button>

    {{ form_end(formCommande) }}
</div>
{% endblock %}

templates/app/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Voir le véhicule{% endblock %}

{% block body %}
<div class="container mt-5">
    <div class="card mb-3 mx-auto">
  <h3 class="card-header">{{ vehicule.titre }}</h3>
  <div class="card-body">
    <h5 class="card-title">{{ vehicule.modele }}</h5>
    <h6 class="card-subtitle text-muted">{{ vehicule.marque }}</h6>
  </div>
  <svg xmlns="http://www.w3.org/2000/svg" class="d-block user-select-none" width="100%" height="200" aria-label="Placeholder: Image cap" focusable="false" role="img" preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle">
    <rect width="100%" height="100%" fill="#868e96"></rect>
    <text x="50%" y="50%" fill="#dee2e6" dy=".3em">{{ vehicule.photo }}</text>
  </svg>
  <div class="card-body">
    <p class="card-text">{{ vehicule.description }}</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">{{ vehicule.prixJournalier }} €/jour</li>
  </ul>
  <div class="card-body">
  {% if app.user %}
      <a href="{{ path('reserve_vehicule', {id: vehicule.id, user: app.user.id}) }}" class="btn btn-success">Réserver ce véhicule</a>
  {% else %}
      <a href="{{ path('app_login') }}" class="btn btn-info">Connectez-vous pour réserver ce véhicule</a>
  {% endif %}
  
{# {% if app.user = admin %}
    <a href="#" class="card-link">Modifier le véhicule</a>
{% endif %} #}
  </div>
    <div class="card-footer text-muted">
        {{ vehicule.dateEnregistrement|date('d/m/Y, H:i:s') }}  </div>
    </div>
</div>

{% endblock %}

templates/app/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mes réservations{% endblock %}

{% block body %}

<div class="container">
<h1 class="text-center mt-4">Mes réservations</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Date de la réservation</th>
                <th>Véhicule</th>
                <th>Début réservation</th>
                <th>Fin réservation</th>
                <th>Prix total</th>
                <th>Options</th>
            </tr>
        </thead>
        <tbody>
            {% for item in commandes %}
                <tr>
                    <td>{{ item.dateEnregistrement|date('d/m/Y, H:i:s') }}</td>
                    <td>{{ item.idVehicule.titre }}</td>
                    <td>{{ item.dateHeureDepart|date('d/m/Y, H:i:s') }}</td>
                    <td>{{ item.dateHeureFin|date('d/m/Y, H:i:s')}}</td>
                    <td>{{ item.prixTotal}}</td>
                    <td>
                        <a href="{{ path('user_commande_edit', {id: item.idMembre.id, order: item.id}) }}" class="btn btn-warning">Modifier la réservation</a>
                        <a href="{{ path('user_delete_commande', {id: item.id}) }}" class="btn btn-danger">Annuler réservation</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% if editMode %}
<div class="container">
    <h2 class="text-center mt-4">Modifier commande</h2>
    {{ form_start(editForm) }}

        {{ form_row(editForm.date_heure_depart) }}
        {{ form_row(editForm.date_heure_fin) }}

    <button class="btn btn-success" type="submit">Enregistrer la commande</button>

    {{ form_end(editForm) }}
</div>
{% endif %}



{% endblock %}